name: dart_pact_consumer
description: A consumer library to build and test pact contracts.
version: 0.1.0
# homepage: https://www.example.com
repository: https://github.com/pak3nuh/dart_pact_consumer/tree/main
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_serializable: ^6.1.1
  json_annotation: ^4.4.0
  path: ^1.8.0
  ffi: ^1.1.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.5
  build_runner: ^2.1.5
